dtb_athena5g:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: athenag5  # Ex: meu-projeto-data ID
      dataset: dbt_dw    # Ex: dbt_maria_julia
      threads: 4
      keyfile: 'c:\Users\Maria Julia\Downloads\athenag5-5bd549bae638.json' # Onde você salvou o JSON do Google
